name: Build Desktop Apps

on:
  # Publish builds when pushing a version tag like v1.2.3
  push:
    tags:
      - "v*"
  # Allow manual runs without publishing
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    env:
      ELECTRON_CACHE: ${{ runner.temp }}/electron
      ELECTRON_BUILDER_CACHE: ${{ runner.temp }}/electron-builder
      CSC_IDENTITY_AUTO_DISCOVERY: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build renderer (Vite)
        run: npm run build:vite

      - name: Build Windows
        if: matrix.os == 'windows-latest'
        run: npm run build:win
        env:
          GH_TOKEN: ${{ startsWith(github.ref, 'refs/tags/') && secrets.GH_TOKEN || '' }}

      - name: Build macOS
        if: matrix.os == 'macos-latest'
        run: npm run build:mac
        env:
          GH_TOKEN: ${{ startsWith(github.ref, 'refs/tags/') && secrets.GH_TOKEN || '' }}

      - name: Build Linux
        if: matrix.os == 'ubuntu-latest'
        run: npm run build:linux
        env:
          GH_TOKEN: ${{ startsWith(github.ref, 'refs/tags/') && secrets.GH_TOKEN || '' }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-artifacts
          path: release/**
          if-no-files-found: ignore
